default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 4 } %>
development:
  <<: *default
  database: caesar_development
test:
  <<: *default
  database: caesar_test
staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
